/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/TheCallForm.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteBreadcrumbs: typeof import('./src/components/SiteBreadcrumbs.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    TheAbout: typeof import('./src/components/TheAbout.vue')['default']
    TheAttendance: typeof import('./src/components/TheAttendance.vue')['default']
    TheBanner: typeof import('./src/components/TheBanner.vue')['default']
    TheCallForm: typeof import('./src/components/TheCallForm.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheGallery: typeof import('./src/components/TheGallery.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    ThePagination: typeof import('./src/components/ThePagination.vue')['default']
    TheSpacer: typeof import('./src/components/TheSpacer.vue')['default']
    VBreadcrumbs: typeof import('./src/components/VBreadcrumbs.vue')['default']
    Zoom: typeof import('./src/components/Zoom.vue')['default']
  }
}
